#%RAML 0.8
title: ad charge
version: v1
mediaType:  application/json

/users/uid/ad_requirements:
  post:
    description: advertiser can post ad requirements
    body:
      application/json:
        example: !include examples/request_201_ad_requirements.json
    responses:
      201:
        headers:
          location:
            example: "users/uid/ad_requirements/adid"
      400:
      403:
        description: current user is not uid
  get:
    description: advertiser can get all ad requirements
    responses:
      200:
        body:
          application/json:
            example: !include examples/response_200_get_all_ad_requirements.json
      403:
        description: current user is not uid
  /adid:
    get:
      description: advertiser can get some ad requirement
      responses:
        200:
          body:
            application/json:
              example: !include examples/response_200_get_ad_requirement.json
        404:
          description: adid not exists; 
        403:
          description: current user is not uid
    /payment:
      post:
        description: advertiser pay for the ad requirement
        body:
          application/json:
            example: !include examples/request_201_payment_for_ad_requirement.json
        responses:
          201:
            headers:
              location:
                example: "users/uid/ad_requirements/adid"
          400:
          404:
            description: adid not exists; 
          403:
            description: current user is not uid
          409:
            description: has paid before
/charge_factors:
  /charge_modes:
    post:
      description: ad alliance admin add a new charge mode for advertiser to choose.
      body:
        application/json:
          example: !include examples/request_201_charge_mode.json
      responses:
        201:
          headers:
            location:
              example: "charge_factors/charge_modes"
        403:
          description: current user is not admin
        400:
    get:
      description: user can get all charge modes available
      responses:
        200:
          body:
            application/json:
              example: !include examples/response_200_get_charge_modes.json
  /website_places:
    post:
      description: ad alliance admin add a new web place for advertiser and webmaster to choose.
      body:
        application/json:
          example: !include examples/request_201_website_place.json
      responses:
        201:
          headers:
            location:
              example: "charge_factors/website_places"
        403:
          description: current user is not admin
        400:
    get:
      description: user can get all web places available
      responses:
        200:
          body:
            application/json:
              example: !include examples/response_200_get_website_places.json
/users/uid/websites:
  get:
    description: webmaster get all the websites in his charge
    responses:
      200:
        body:
          application/json:
            example: !include examples/response_200_get_websites.json
      403:
        description: current user is not uid
  /wid:
    /webmaster_contracts:
      post:
        description: webmaster can apply for joining the platform with some conditions.
        body:
          application/json:
            example: !include examples/request_201_webmaster_contract.json
        responses:
          201:
            headers:
              location:
                example: "users/uid/websites/wid/webmaster_contracts/wcid"
          403:
            description: current user is not uid
      /wcid:
        get:
          description: webmaster can get some contract detail
          body:
            application/json:
              example: !include examples/response_200_get_website_contract.json
          responses:
            200:
            403:
              description: current user is not uid
    /histories:
      get:
        description: get the click and view histories of website
        queryParameters:
          action: 
            type: string
            example: "CLICK | VIEW"
          startDate:
            type: integer
          endDate:
            type: integer
          ad:
            type: string
            description: the ad_requirement id
        responses:
          200:
            body:
              application/json:
                example: !include examples/response_200_get_histories.json
          403:
            description: current user is not uid or admin
    /ad_releases:
      post:
        description: admin releases the ad on the website
        body:
          application/json:
            example: !include examples/request_201_ad_release.json
        responses:
          201:
            headers:
              location:
                example: "users/uid/websites/wid/ad_releases/rid/"
          403:
            description: not admin
          400:
      /rid:
        get:
          description: webmaster can the release info of some ad, including revenue until now
          responses:
            200:
              body:
                application/json:
                  example: !include examples/response_200_get_ad_release.json
            403:
              description: current user is not uid
            404:
        /revenue:
          get:
            description: admin get the revenue of some ad releasement from startDate to endDate. admin can get the total revenue of an ad release, which is the pure benefit of the platform
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response_200_get_revenue.json
              403:
                description: not admin
        /payment:
          post:
            description: admin can pay for the webmaster. This can be done automatically
            body:
              application/json:
                example: !include examples/request_201_payment_for_web_master.json
            responses:
              201:
                headers:
                  location:
                    example: "users/uid/websites/wid/ad_releases/rid"
              403:
                description: not admin
              400:
                description: incomplete input; admin has paid for the specified date 
        /removal:
          post:
            description: admin/webmaster can remove the ad from website
            body:
              application/json:
                example: !include examples/request_201_removal_of_ad.json
            responses:
              201:
                headers:
                  location:
                    example: "users/uid/websites/wid/ad_releases/rid"
              403:
                description: not admin or webmaster
              409:
                description: has been removed





